version: "3.3"

volumes:
  pg_data:
  media:
  static:
  docs:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: r4zeel/sagaart_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/backend_static
      - docs:/app/static/data/docs
    depends_on:
      - db
  gateway:
    image: r4zee/sagaart_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - docs:/usr/share/nginx/html/api/docs
      - media:/media
    depends_on:
      - backend
